services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - backend
      - sockets

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - OPEN_AI_KEY=${OPEN_AI_KEY}
      - DATABASE_URI=database
      - ATLAS_URI=${ATLAS_URI}
    # depends_on:
    #   - database
    # entrypoint: [ "wait-for-it.sh", "database:27017", "--", "npm", "start" ]

  sockets:
    build:
      context: ./sockets
      dockerfile: Dockerfile
    ports:
      - 3002:3002
  # database:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./mongodb_data:/data/db

volumes:
  mongodb_data:
