name: 🚀 Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted # Changed from 'ubuntu-latest' to use your self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application
        run: |
          # Since we're already on the EC2 instance, no need for SSH
          cd ~/Cloud  # Navigate to your project directory
          git pull origin main
          docker-compose pull
          docker-compose -f docker-compose.prod.yml up -d --build
